version: '3.7'

services:
  poor-clares-arundel-koa:
    image: poor-clares-arundel-koa
    build: .
    environment:
      NODE_ENV: production
      APPSETTINGS_API_KEY: 'api-key-from-mailgun'
      APPSETTINGS_DOMAIN: 'mg.poorclaresarundel.org'
      APPSETTINGS_PRAYER_REQUEST_FROM_EMAIL: 'noreply@mg.poorclaresarundel.org'
      APPSETTINGS_PRAYER_REQUEST_RECIPIENT_EMAIL: 'johnny_reilly@hotmail.com'
    ports:
      - 3000:3000