version: '3.7'

services:
  mailer:
    image: mailer
    build: .
    environment:
      # DOTNET_ENVIRONMENT: Production
      # ASPNETCORE_URLS: 'http://+:5000'
      # DOTNET_URLS: 'http://+:5000'
      # DOTNET_URLS: 'http://localhost:5000'
      DAPR_HTTP_PORT: '3500'
      DAPR_GRPC_PORT: '50000'
      DAPR_METRICS_PORT: '9090'
      # NODE_ENV: production
      # APPSETTINGS_API_KEY: 'this is the guid from mailgun'
      # APPSETTINGS_DOMAIN: 'mg.priou.co.uk'
      # APPSETTINGS_PRAYER_REQUEST_FROM_EMAIL: 'noreply@mg.priou.co.uk'
      # APPSETTINGS_PRAYER_REQUEST_RECIPIENT_EMAIL: 'info@priou.co.uk'
    ports:
      - 5000:5000

# docker build --tag mailer .
# docker-compose up
# get into the container
# docker run -it --entrypoint sh mailer
# docker run --name mailer -p 5000:80 -d mailer