name: Container

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  container-build:
    uses: ./.github/workflows/shared-build-and-deploy.yaml
    with:
      deploy: false
    secrets: inherit
