name: Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  RESOURCE_GROUP: rg-aca
  LOCATION: westeurope
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy bicep
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group create -g ${{ env.RESOURCE_GROUP }} -l ${{ env.LOCATION }}
            az deployment group create -g ${{ env.RESOURCE_GROUP }} -f ./infra/main.bicep \
             -p \
                subscriptionId='${{ secrets.SUBSCRIPTION_ID }}'
                name='container-app'
