name: Pull request comment

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  output-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

  build-and-deploy:
    # check if the comment comes from a pull request and contains the required keyword
    if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/deploy')
    uses: ./.github/workflows/shared-build-and-deploy.yaml
    with:
      deploy: true
    secrets: inherit
